require('./schema/admin/adminDetails')
require('./schema/bookingRecord/customizedtripRecord')
require('./schema/bookingRecord/tourRecord')
require('./schema/bookingRecord/tripRecord')

require('./schema/user/userComplain')
require('./schema/user/userCustomizedTrips')
require('./schema/user/userDetails')
require('./schema/user/userFlights')
require('./schema/user/userTours')

require('./schema/vendor/TripsOrganized')
require('./schema/vendor/toursOrganized')
require('./schema/vendor/tripsBidded')
require('./schema/vendor/vendorComplains')
require('./schema/vendor/vendorDetails')
